//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsYonetimDBEntities : DbContext
    {
        public IsYonetimDBEntities()
            : base("name=IsYonetimDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gorevlendirme> Gorevlendirmes { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Yonetici> Yoneticis { get; set; }
        public virtual DbSet<Izin> Izins { get; set; }
    }
}
