//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Gorevlendirme
    {
        public int gorev_id { get; set; }
        public int personel_id { get; set; }
        public int yonetici_id { get; set; }
        [DisplayName("Gorev Adi")]
        public string gorev_adi { get; set; }
        [DisplayName("Gorev Tanimi")]
        [DataType(DataType.MultilineText)]
        public string gorev_tanimi { get; set; }

        public virtual Personel Personel { get; set; }
        public virtual Yonetici Yonetici { get; set; }
    }
}
