//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Görevlendirme
    {
        public string yonetici_kullanici_adi { get; set; }
        public string personel_kullanici_adi { get; set; }
        public string gorev_adi { get; set; }
        public string gorev_tanimi { get; set; }
    }
}
