//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Izin
    {
        public int izin_id { get; set; }
        public int personel_id { get; set; }
        public int yonetici_id { get; set; }
        [DisplayName("Izin sebebi")]
        public string izin_sebebi { get; set; }
        [DisplayName("Izin Baslangic Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-mm-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime izin_baslangic_tarihi { get; set; }
        [DisplayName("Izin Bitis Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-mm-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime izin_bitis_tarihi { get; set; }

        public virtual Yonetici Yonetici { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
