//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave
    {
        public int leave_id { get; set; }
        public int personnel_id { get; set; }
        public int manager_id { get; set; }
        [DisplayName("Izin sebebi")]
        public string leave_reason { get; set; }
        [DisplayName("Izin Baslangic Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime leave_start_date { get; set; }
        [DisplayName("Izin Bitis Tarihi")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime leave_end_date { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
