//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manager()
        {
            this.Tasks = new HashSet<Task>();
            this.Leaves = new HashSet<Leave>();
        }
    
        public int user_id { get; set; }
        [DisplayName("Kullanici Adi")]
        [Required(ErrorMessage = "Bu alanin doldurulmasi gereklidir.")]
        public string username { get; set; }
        [DisplayName("Parola")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bu alanin doldurulmasi gereklidir.")]
        public string password { get; set; }
        [DisplayName("Parolayi Dogrulayin")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string confirm_password { get; set; }
        [DisplayName("Ad")]
        [Required(ErrorMessage = "Bu alanin doldurulmasi gereklidir.")]
        public string first_name { get; set; }
        [DisplayName("Soyad")]
        [Required(ErrorMessage = "Bu alanin doldurulmasi gereklidir.")]
        public string last_name { get; set; }
        [DisplayName("E-Mail")]
        [Required(ErrorMessage = "Bu alanin doldurulmasi gereklidir.")]
        public string email { get; set; }
        [DisplayName("Maas")]
        [Required(ErrorMessage = "Bu alanin doldurulmasi gereklidir.")]
        public Nullable<int> salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
    }
}
