//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        public int task_id { get; set; }
        public int personnel_id { get; set; }
        public int manager_id { get; set; }
        [DisplayName("Gorev Adi")]
        public string task_name { get; set; }
        [DisplayName("Gorev Tanimi")]
        [DataType(DataType.MultilineText)]
        public string task_detail { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
